# Lab exercise, week 3 - numpy & matplotlib basics

Contents:
- Overview of numpy arrays
- Exercises for numpy
- Exercises for plotting

## NumPy - overview

Python lists are somewhat weird creatures. In contrast to basic array types in other languages like C# and Java, they can hold objects of different types and new elements can be inserted in the middle. NumPy arrays are much more like C# arrays - all elements have the same type.

In [ ]:
# by convention numpy is always imported as np
import numpy as np

### Common ways of creating numpy arrays

In [ ]:
a = np.array([5, 2, 17])  # Convert a Python list into a numpy array
a

array([ 5,  2, 17])

In [ ]:
# List of lists gets converted into a 2D array
np.array([[5, 7, 2],
          [9, 4, 1]])


array([[5, 7, 2],
       [9, 4, 1]])

In [ ]:
np.arange(5)  # Same as Python's range() but creates a numpy array

array([0, 1, 2, 3, 4])

In [ ]:
np.zeros(5)  # Create a numpy array with five elements, all set to zero

array([0., 0., 0., 0., 0.])

In [ ]:
c = np.ones(7)  # Create a numpy array with five elements, all set to 1
c


array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Array of 6 random numbers between 0 and 1
np.random.rand(6)

array([0.14654318, 0.24300736, 0.74564537, 0.58652819, 0.39433085,
       0.94389319])

In [ ]:
# array with 6 random integers between 0 and 100 (not including 100 as usual)
np.random.randint(100, size=6)

array([64, 97,  1, 69, 74, 72])

### Array properties

In [ ]:
b = np.array([[5, 7, 2],
              [9, 4, 1]])
b

array([[5, 7, 2],
       [9, 4, 1]])

In [ ]:
# Data type of the array
a.dtype

dtype('int64')

In [ ]:
# number of dimensions
b.ndim

2

In [ ]:
# array shape is a Python tuple, in this case it's (2, 3) because b is a 2 by 3 array.
b.shape

(2, 3)

In [ ]:
# The total number of elements
b.size

6

In [ ]:
# Note that zeros byt default uses the float64 data type
z = np.zeros(7)
z.dtype

dtype('float64')

In [ ]:
# But data type can be set explicitly, almost all numpy functions that create arrays take an optional dtype parameter
# Let's set it to an 8 bit integer
z = np.zeros(7, dtype=np.int8)
z.dtype

dtype('int8')

## Exercises

Read section 2.2 of the book (The Basics of NumPy Arrays) and complete the tasks below.


### 1. Numpy Array Creation

##### Convert a list into a numpy array

In [ ]:
lst = [5, 3, 8, 4]
lst

[5, 3, 8, 4]

In [2]:
import numpy as np
lst = [5, 3, 8, 4]
x = np.array(lst)
print(x)

[5 3 8 4]


#### What happens when you multiply a list by 3, what a about an array multiplied by 3?

In [4]:

print(lst * 3)
print(x * 3)

[5, 3, 8, 4, 5, 3, 8, 4, 5, 3, 8, 4]
[15  9 24 12]


#### Create an array of 10 ones [1, 1, 1, ... ]

In [5]:
ones = np.ones(10, dtype=int)
print(ones)

[1 1 1 1 1 1 1 1 1 1]


#### Create an array of 10 fives [5, 5, 5, .... ]

In [6]:
fives = np.full(10, 5)
print(fives)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50 (including 50)

In [7]:
arr_10_50 = np.arange(10, 51)
print(arr_10_50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of 10 random numbers between 0 and 5

In [8]:
rand_0_5 = np.random.rand(10) * 5
print(rand_0_5)

[4.62748023 1.26277625 2.99440657 2.25433477 0.37016027 4.27557457
 1.29618037 3.07355684 0.16906517 4.66083575]


#### Read the help for np.linspace function and create an array of 11 evenly spaced elements between 0 and 2
use `np.linspace?` or `?np.linspace` to show the help

In [9]:
lin = np.linspace(0, 2, 11)   # 11 values from 0 to 2 inclusive
print(lin)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


#### Create a 3 by 4 array of ones

In [10]:
ones_3x4 = np.ones((3,4), dtype=int)
print(ones_3x4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


#### Create a 3 by 4 array of fives

In [11]:
fives_3x4 = np.full((3,4), 5)
print(fives_3x4)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


### 2. Array Indexing
Using the following arrays `a` and `m` for the questions below

In [ ]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
m = np.arange(1,22).reshape((3,7))
m

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

### Create an array containing...
#### the first 4 elements of a

In [ ]:
print(a[:4])

array([10, 11, 12, 13])

#### the last 3 elements of a

In [ ]:
print(a[-3:])

#### The middle elements of a from 15 to 18 inclusive

In [ ]:
print(a[5:9])

#### The first column of m

In [ ]:
print(m[:,0])

#### The middle row of m

In [ ]:
print(m[1])

#### The left 3 columns of m

In [ ]:
print(m[:, :3])

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [15, 16, 17]])

#### The bottom-right 2 by 2 square

In [ ]:
print(m[1:, -2:])

array([[13, 14],
       [20, 21]])

#### Print every other element of a
Hint: use slicing with a step (`array[start:stop:step]`)

In [ ]:
print(a[::2])

array([10, 12, 14, 16, 18, 20])

#### Print the `even` elements of a
Hint: use boolean indexing

In [ ]:
print(a[a % 2 == 0])

### 3. Array Math

#### Subtract 5 from each element of a

In [ ]:
print(a - 5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Calculate the `sum` of all the elements in a

In [ ]:
print(a.sum())

#### Calculate the sum of each column and each row in `m`
Hint: use the `axis` argument of the `sum` method

In [ ]:
print(m.sum(axis=0))
print(m.sum(axis=1))

#### Create an array containing squares of all numbers from 1 to 10 (inclusive)

In [ ]:
squares = np.arange(1,11)**2
print(squares)

#### Create an array containing all powers of 2 from $2^0$ to $2^{10}$ (inclusive)

In [ ]:
powers_of_two = 2 ** np.arange(0, 11)
print(powers_of_two)

#### Same as above (powers of two), but subtract one from each element, that is $a_k = 2^k - 1$

In [ ]:
powers_minus1 = powers_of_two - 1
print(powers_minus1)

### 4. Plotting Basics
 - Use [this tutorial](https://matplotlib.org/users/pyplot_tutorial.html) as reference when (if) you get stuck
 - Execute the cells with imports, otherwise you won't have numpy and matplotlib imported and Python will complain

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Load weather data (take a look at that CSV file on GitHub or via Excel and note column names)
weather = np.loadtxt("OshawaWeather2016.csv", skiprows=1, delimiter=',')

In [ ]:
weather.shape

(349, 5)

In [ ]:
weather.dtype

dtype('float64')

#### Crate separate 1D arrays for each column (e.g: day, maxt, mint and so on)

In [ ]:
day = weather[:,0]
maxt = weather[:,1]
mint = weather[:,2]
meant = weather[:,3]
precip = weather[:,4]

#### Plot the minimum temperature as a function of day number

#### Plot the max temperature in degrees Fahrenheit

#### Plot the difference between the maximum and the minimum day temperature as a function of day number

#### Plot both, the minimum and maximum temperature on the same figure

In [ ]:
plt.plot(day, mint, label="Min Temp (°C)")
plt.plot(day, maxt, label="Max Temp (°C)")
plt.xlabel("Day")
plt.ylabel("Temperature (°C)")
plt.title("Daily Min and Max Temps")
plt.legend()
plt.show()

#### Add axis labels and a legend to the plot above
Use the following functions:
 - plt.xlabel
 - plt.ylabel
 - plt.title
 - plt.legend

#### Read about plt.hist() function and plot a histogram of the maximum temperatures

In [ ]:
plt.hist(maxt, bins=20, color="orange")
plt.xlabel("Max Temp (°C)")
plt.ylabel("Frequency")
plt.title("Distribution of Max Temperatures")
plt.show()

#### Plot a histogram of the differences between the min and max temperature

In [ ]:
plt.hist(maxt - mint, bins=20, color="green")
plt.xlabel("Temperature Range (°C)")
plt.ylabel("Frequency")
plt.title("Distribution of Daily Temp Ranges")
plt.show()

#### For each day calculate the average of the 3 temperatures in the data (min max and avg)


In [ ]:
daily_avg = (maxt + mint + meant) / 3
print("First 5 daily averages:", daily_avg[:5])

#### Calculate the total amount of precipitation for the whole year
Does the number seem reasonable? The annual average precipitation in Toronto is 831 mm according to https://en.wikipedia.org/wiki/Geography_of_Toronto

In [ ]:
total_precip = precip.sum()
print("Total Precipitation (mm):", total_precip)

#### Calculate the total precipitation on all odd numbered days (day 1, 3, 5 and so on)

In [ ]:
odd_precip = precip[day % 2 == 1].sum()
print("Total Precip on Odd Days (mm):", odd_precip)